export const COUNTER_TYPES = {
	INCREMENT_COUNTER: 'ADD_COUNTER',
	DECREMENT_COUNTER: 'SUBTRACT_COUNTER',
    RESET_COUNTER: 'RESET_COUNTER',
    INCREMENT_STEPS:'INCREMENT_STEPS',
    DECREMENT_STEPS: 'DECREMENT_STEPS',
    RESET_STEPS: 'RESET_STEPS',
};
